apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
  name: my-annotation-setting
spec:
  targetRef:
    group: content.halo.run
    kind: Post
  formSchema:
    - $formkit: "checkbox"
      name: "summary.xhhao.com/enable-black-list"
      label: "禁用AI摘要-智阅GPT"
      on-value: "true"
      off-value: "false"
    - $formkit: "checkbox"
      name: "summary.xhhao.com/update-summary"
      label: "手动更新摘要-智阅GPT"
      on-value: "true"
      off-value: "false"